// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoClub.Data.Context;

#nullable disable

namespace VideoClub.Data.Migrations
{
    [DbContext(typeof(VideoClubDbContext))]
    [Migration("20231001214549_InitialLoad")]
    partial class InitialLoad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoClub.Data.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasRenta")
                        .HasColumnType("Int");

                    b.Property<decimal>("EntregaTardia")
                        .HasColumnType("Decimal(8,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("RentaDia")
                        .HasColumnType("Decimal(8,2)");

                    b.Property<int>("TipoArticuloId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VarChar(600)");

                    b.HasKey("Id");

                    b.ToTable("Articulos", "dbo");
                });

            modelBuilder.Entity("VideoClub.Data.Entities.Idioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Idiomas", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Español",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Ingles",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Frances",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("VideoClub.Data.Entities.TipoArticulo", b =>
                {
                    b.Property<int>("TipoArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoArticuloId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("TipoArticuloId");

                    b.ToTable("TiposArticulos", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
